import './globals.css'
import { geliatFont, bluuNextFont, ibmPlexMono } from '@/styles/fonts'
import clsx from 'clsx'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={clsx(geliatFont.variable, bluuNextFont.variable, ibmPlexMono.variable, 'font-sans')}>
      <body>{children}</body>
    </html>
  )
}
